### ISSUE TITLE
Arrival/Departure time is not included in the API call and therefore does not do anything usefull at the moment

### ISSUE THREAD

**Issue by MadsHeilmann** [audio-engineer/aau-p1-software#45]
In the below run of the program, the time is not accounted for:

C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/zsh -c "cd /mnt/c/Users/madsh/OneDrive/Dokumenter/GitHub/aau-p1-software/cmake-build-debug && /mnt/c/Users/madsh/OneDrive/Dokumenter/GitHub/aau-p1-software/cmake-build-debug/aau_p1_software"
Use predefined or manually input? (p = predefined or m = manual) :m
 m
Start location :farum st
 farum st
End location :vigerslev alle st
 vigerslev alle st
Do you want to plan routes for Departure time? (y) Or Arrival time? (n):y
 y
Input arrival/departure hour:12
 12
Input arrival/departure minutes :30
 30
Do you want to manually input your preferenes? (m)
Load preferences from a file (f)
Use presets? (p)
       >>>p
 p
Request will be made to URL: https://xmlopen.rejseplanen.dk/bin/rest.exe/location?input=farum%20st&format=json
Request will be made to URL: https://xmlopen.rejseplanen.dk/bin/rest.exe/location?input=vigerslev%20alle%20st&format=json
Origin location ID: 008600696
Destination location ID: 008600804
Request will be made to URL: https://xmlopen.rejseplanen.dk/bin/rest.exe/trip?originId=008600696&destId=008600804&format=json&useBus=0
There are 3 distinct routes available for this trip.
Request will be made to URL: http://webapp.rejseplanen.dk/bin//rest.exe/journeyDetail?ref=889065%2F348440%2F394726%2F98992%2F86%3Fdate%3D18.12.23%26station_evaId%3D8600696%26format%3Djson
Leg: 1, number of stops: 12
Request will be made to URL: http://webapp.rejseplanen.dk/bin//rest.exe/journeyDetail?ref=840564%2F301973%2F197710%2F181340%2F86%3Fdate%3D18.12.23%26station_evaId%3D8600644%26format%3Djson
Leg: 2, number of stops: 10
Total number of stops on trip: 22

Priority 1: ID:          2 P: 240.00 T:  18.00 E: 374.00 --- Ps: 1.00 Ts: 1.00 Es: 0.00 --- Os: 1.00.
Priority 2: ID:          0 P: 381.00 T: 304.00 E: 219.00 --- Ps: 0.40 Ts: 0.00 Es: 0.43 --- Os: 0.34.
Priority 3: ID:          1 P: 474.00 T:  75.00 E:  17.00 --- Ps: 0.00 Ts: 0.80 Es: 1.00 --- Os: 0.20.

View route details (number), sort the list (Price (P),Time (T), Environment (E), Overall (O)) or terminate (Q):1
  1
You entered: 1
Number of legs in the chosen trip: 2
--------------------------------------------------
Leg 1:
Transportation name:       B
Transportation type:       S

Origin station name:       Farum St.
Origin station time:       19:31
Origin station date:       18.12.23
Origin station Track:      2

Destination station name:  Ryparken St.
Destination station time:  19:56
Destination station date:  18.12.23
Destination station Track: 2
--------------------------------------------------
Leg 2:
Transportation name:       F
Transportation type:       S

Origin station name:       Ryparken St.
Origin station time:       20:04
Origin station date:       18.12.23
Origin station Track:      12

Destination station name:  Vigerslev Alle St.
Destination station time:  20:17
Destination station date:  18.12.23
Destination station Track: 12
--------------------------------------------------
View route details (number), sort the list (Price (P),Time (T), Environment (E), Overall (O)) or terminate (Q):

**Comment by audio-engineer** [comment]
@MadsHeilmann Thanks for the input. I agree, but I think it was just not accounted for originally. We _should_ implement it, though...

**Comment by Danar435** [comment]
**From the documentation:** 
The departure time and date are defined with the parameters date and time. If the date is not set the current date will be used (server time). If the parameter time is not set the current server time will be used to perform the request. It is possible to search for latest arrival time instead of departure time by adding the parameter searchForArrival=1.

So when generating the link for the journey, it should include `&time=HH:MM` and if the time is for arrival, then add `&searchForArrival=1`

**Comment by audio-engineer** [comment]
@Danar435 Thank you, I have read the documentation.
